export default {
  locale: "pt-BR",
  githubUser: "ThierryDev499",
  labels: {
    github: "GitHub",
    demo: "Demo",
    githubFor: "Ver {name} no GitHub",
    demoFor: "Abrir demonstração de {name}",
    updated: "Atualizado em {date}",
    repository: "Código disponível",
    unavailable:
      "As atualizações do GitHub estão temporariamente indisponíveis. Os projetos continuam acessíveis pelos links.",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
  },
  projects: [
    {
      slug: "simplea-sales-ai",
      repository: "Sales-Comercial",
      status: "published",
      name: "Simplea Sales AI",
      category: "IA APLICADA / SISTEMAS DE NEGÓCIO",
      description:
        "Aplicação desktop que reúne CRM, chat comercial com IA e consulta à base de conhecimento da empresa.",
      stack: [
        "TypeScript",
        "Node.js",
        "Fastify",
        "React",
        "Electron",
        "SQLite",
      ],
      highlights: [
        "CRM com leads, pipeline e acompanhamento comercial.",
        "Base de conhecimento com embeddings e busca RAG.",
        "Integração com múltiplos provedores de modelos de IA.",
      ],
      demo: null,
    },
    {
      slug: "ai-document-intelligence",
      repository: "ai-document-intelligence",
      status: "published",
      name: "AI Document Intelligence",
      category: "IA LOCAL / DOCUMENTOS / RAG",
      description: "Workspace para importar PDFs, gerar resumos e consultar documentos com IA local e fontes verificáveis.",
      problem: "Reduz a leitura manual para localizar informações em documentos operacionais.",
      stack: ["Python", "FastAPI", "Ollama", "NumPy", "SQLite"],
      highlights: ["Extração por página, chunking e embeddings locais.", "Perguntas com RAG, trechos de origem e histórico.", "Validação de arquivos e testes automatizados da API."],
      screenshot: "assets/projects/ai-document-intelligence.png",
      demo: null,
    },
    {
      slug: "automation-orchestrator",
      repository: "automation-orchestrator",
      status: "published",
      name: "Automation Orchestrator",
      category: "RPA / BACKEND / OPERAÇÕES",
      description: "Console de execução de automações com fila persistente, tentativas automáticas e rastreabilidade por execução.",
      problem: "Centraliza o acompanhamento de scripts que antes dependiam de execução e conferência manuais.",
      stack: ["TypeScript", "Node.js", "Fastify", "SQLite", "Docker"],
      highlights: ["Cadastro, edição, parâmetros e ativação de automações.", "Fila, retries, histórico, logs e resultados persistidos.", "Scripts de CSV, relatórios e consulta real à BrasilAPI."],
      screenshot: "assets/projects/automation-orchestrator.png",
      demo: null,
    },
    {
      slug: "ai-support-agent",
      repository: "ai-support-agent",
      status: "published",
      name: "AI Support Agent",
      category: "IA LOCAL / ATENDIMENTO / RAG",
      description: "Triagem de chamados com classificação por IA local, consulta à base de conhecimento e revisão humana das respostas.",
      problem: "Organiza a busca por procedimentos e a preparação de respostas para solicitações recorrentes.",
      stack: ["Python", "FastAPI", "Ollama", "RAG", "SQLite"],
      highlights: ["Categoria, intenção, urgência e prioridade sugeridas por IA.", "Respostas com referências aos artigos consultados.", "Edição, aprovação humana, filtros e histórico do chamado."],
      screenshot: "assets/projects/ai-support-agent.png",
      demo: null,
    },
    {
      slug: "cnpj-lookup",
      repository: "cnpj-lookup",
      status: "published",
      name: "CNPJ Lookup",
      category: "APIs / DADOS EMPRESARIAIS",
      description:
        "Consulta de dados empresariais conectada a uma API pública, com leitura estruturada das informações cadastrais.",
      stack: ["React", "TypeScript", "Vite", "REST API"],
      highlights: [
        "Consulta direta à API pública de CNPJ.",
        "Renderização de dados e objetos JSON aninhados.",
        "Tratamento de erros e compartilhamento por link.",
      ],
      demo: "https://thierrydev499.github.io/cnpj-lookup/",
    },
  ],
};
